### ISSUE TITLE
file-checksum throwing error

### ISSUE THREAD

**Issue by Kaali09** [thatisuday/file-checksum#1]
I have installed the file-checksum in ubuntu 16.04 and it is thorwing error when i run file-checksum -v as below, 

`➜ file-checksum -v
/usr/local/lib/node_modules/file-checksum/index.js:14
const { ALGORITHMS } =  require( './lib/constants' );
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

Any suggestions?

**Comment by thatisuday** [comment]
@Kaali09 You could be using very old version of Node.js. What's your current Node version?
